
import { Product, ContactProfile, InvoiceFormat } from './types';
import { addTransactionLog } from './storageUtils';

export const generateInvoiceText = (profile: ContactProfile): string => {
  const { name, products } = profile;
  
  let totalAmount = 0;
  let totalPaid = 0;
  
  const productLines = products.map(product => {
    const balance = product.price - product.paidAmount;
    totalAmount += product.price;
    totalPaid += product.paidAmount;
    
    return `*${product.name}*
Price: $${product.price.toFixed(2)}
Paid: $${product.paidAmount.toFixed(2)}
Balance: $${balance.toFixed(2)}
-----------------`;
  }).join('\n');
  
  const totalBalance = totalAmount - totalPaid;
  
  const message = `*INVOICE FOR ${name.toUpperCase()}*
Date: ${new Date().toLocaleDateString()}

${productLines}

*SUMMARY*
Total Amount: $${totalAmount.toFixed(2)}
Total Paid: $${totalPaid.toFixed(2)}
Total Balance: $${totalBalance.toFixed(2)}

Thank you for your business!
Generated by QuickBill Connect`;

  return message;
};

export const formatWhatsAppText = (text: string): string => {
  // WhatsApp already supports * for bold, so we don't need to modify the text
  return text;
};

export const sendViaWhatsApp = (
  profile: ContactProfile,
  format: InvoiceFormat,
  selectedProducts: Product[]
): void => {
  const { phoneNumber } = profile;
  
  // Create a subset profile with only selected products
  const subsetProfile = {
    ...profile,
    products: selectedProducts
  };
  
  // Generate invoice text
  const invoiceText = generateInvoiceText(subsetProfile);
  
  // Format text for WhatsApp and encode it
  const formattedText = formatWhatsAppText(invoiceText);
  const encodedText = encodeURIComponent(formattedText);
  
  // Create WhatsApp URL
  const whatsappUrl = `https://wa.me/${phoneNumber.replace(/\+/g, '')}?text=${encodedText}`;
  
  // Log the transaction
  addTransactionLog({
    contactId: profile.contactId,
    contactName: profile.name,
    date: new Date().toISOString(),
    type: 'message',
    content: `Invoice sent via WhatsApp (${format})`,
    products: selectedProducts
  });
  
  // Open WhatsApp
  window.open(whatsappUrl, '_blank');
};

// PDF generation would require a library like jsPDF
// This is a placeholder function
export const generatePdfInvoice = async (profile: ContactProfile): Promise<string> => {
  // This would normally generate a PDF using a library
  // For now, we'll just return a message
  return "PDF generation would require additional libraries";
};

// Image generation would require an HTML-to-image library
// This is a placeholder function
export const generateImageInvoice = async (profile: ContactProfile): Promise<string> => {
  // This would normally generate an image using a library
  // For now, we'll just return a message
  return "Image generation would require additional libraries";
};
